/* Generated By:JavaCC: Do not edit this line. MyRelationConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyRelationConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int SIGMA = 6;
  /** RegularExpression Id. */
  int PI = 7;
  /** RegularExpression Id. */
  int JOIN = 8;
  /** RegularExpression Id. */
  int CARTPROD = 9;
  /** RegularExpression Id. */
  int FUNCTION = 10;
  /** RegularExpression Id. */
  int INTERSECTION = 11;
  /** RegularExpression Id. */
  int UNION = 12;
  /** RegularExpression Id. */
  int MINUS = 13;
  /** RegularExpression Id. */
  int DIVIDE = 14;
  /** RegularExpression Id. */
  int Y = 15;
  /** RegularExpression Id. */
  int RENAME = 16;
  /** RegularExpression Id. */
  int OPEN_PAR = 17;
  /** RegularExpression Id. */
  int CLOSE_PAR = 18;
  /** RegularExpression Id. */
  int DOT = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int QUO = 21;
  /** RegularExpression Id. */
  int OPERATOR = 22;
  /** RegularExpression Id. */
  int DIGITS = 23;
  /** RegularExpression Id. */
  int NAME = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AND\"",
    "\"\\u03c3\"",
    "\"\\u03c0\"",
    "\"\\u2a1d\"",
    "\"\\u2a2f\"",
    "\"\\u2131\"",
    "\"\\u2229\"",
    "\"\\u222a\"",
    "\"\\u2212\"",
    "\"\\u00f7\"",
    "\"\\u03b3\"",
    "\"Set\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "<QUO>",
    "<OPERATOR>",
    "<DIGITS>",
    "<NAME>",
  };

}
