/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "structs.h"

bool_t
xdr_toManageStruct (XDR *xdrs, toManageStruct *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->value))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->time))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentNumber))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeEnd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeStart))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->type);
			IXDR_PUT_LONG(buf, objp->value);
			IXDR_PUT_LONG(buf, objp->time);
			IXDR_PUT_LONG(buf, objp->currentNumber);
			IXDR_PUT_LONG(buf, objp->currentRangeEnd);
			IXDR_PUT_LONG(buf, objp->currentRangeStart);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->value))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->time))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentNumber))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeEnd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeStart))
				 return FALSE;
		} else {
			objp->type = IXDR_GET_LONG(buf);
			objp->value = IXDR_GET_LONG(buf);
			objp->time = IXDR_GET_LONG(buf);
			objp->currentNumber = IXDR_GET_LONG(buf);
			objp->currentRangeEnd = IXDR_GET_LONG(buf);
			objp->currentRangeStart = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->time))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->currentNumber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->currentRangeEnd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->currentRangeStart))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_toComputeStruct (XDR *xdrs, toComputeStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->end))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_toReportStruct (XDR *xdrs, toReportStruct *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->hostName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (7 +  10 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->perfectNumbers, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->perfectNumberIndex))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numberTested))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->range))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeStart))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeEnd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentNumber))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->fd);
			{
				register int *genp;

				for (i = 0, genp = objp->perfectNumbers;
					i < 10; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->perfectNumberIndex);
			IXDR_PUT_LONG(buf, objp->numberTested);
			IXDR_PUT_LONG(buf, objp->range);
			IXDR_PUT_LONG(buf, objp->currentRangeStart);
			IXDR_PUT_LONG(buf, objp->currentRangeEnd);
			IXDR_PUT_LONG(buf, objp->currentNumber);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->hostName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (7 +  10 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->perfectNumbers, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->perfectNumberIndex))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numberTested))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->range))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeStart))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentRangeEnd))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->currentNumber))
				 return FALSE;
		} else {
			objp->fd = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->perfectNumbers;
					i < 10; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->perfectNumberIndex = IXDR_GET_LONG(buf);
			objp->numberTested = IXDR_GET_LONG(buf);
			objp->range = IXDR_GET_LONG(buf);
			objp->currentRangeStart = IXDR_GET_LONG(buf);
			objp->currentRangeEnd = IXDR_GET_LONG(buf);
			objp->currentNumber = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->hostName, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->perfectNumbers, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->perfectNumberIndex))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numberTested))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->range))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->currentRangeStart))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->currentRangeEnd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->currentNumber))
		 return FALSE;
	return TRUE;
}
