/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRUCTS_H_RPCGEN
#define _STRUCTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct toManageStruct {
	int type;
	int value;
	int time;
	int currentNumber;
	int currentRangeEnd;
	int currentRangeStart;
};
typedef struct toManageStruct toManageStruct;

struct toComputeStruct {
	int type;
	int start;
	int end;
};
typedef struct toComputeStruct toComputeStruct;

struct toReportStruct {
	char hostName[20];
	int fd;
	int perfectNumbers[10];
	int perfectNumberIndex;
	int numberTested;
	int range;
	int currentRangeStart;
	int currentRangeEnd;
	int currentNumber;
};
typedef struct toReportStruct toReportStruct;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_toManageStruct (XDR *, toManageStruct*);
extern  bool_t xdr_toComputeStruct (XDR *, toComputeStruct*);
extern  bool_t xdr_toReportStruct (XDR *, toReportStruct*);

#else /* K&R C */
extern bool_t xdr_toManageStruct ();
extern bool_t xdr_toComputeStruct ();
extern bool_t xdr_toReportStruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRUCTS_H_RPCGEN */
